### ISSUE TITLE
Option to disable things like KDE-games-meta in installer

### ISSUE THREAD

**Issue by nigelwarning** [arcolinuxd/arco-plasma#3]
So,

I love my KDE as minimal as possible, which I mostly do with archfi,
but I don't want all the game packages and stuff. Is it possbile to create a option to disable these kind of packages. I want a vanilla Arch install with the arco theme, but not games-meta, education-meta.

Maybe option to choose with one to install? And maybe a option to choose between plasma or plasme-meta.

**Comment by arcolinuxz** [comment]
you edit the scripts anyway you see fit.

You reported this on ArcoLinuxD.

But there is an https://arcolinuxb.com websites where you can built your own Plasma version you want.

That is much easier and faster to install afterwards.
